#%RAML 1.0
title: Event Subscription
baseUri: www.localhost.com/
version: v1

# ------------------------------------------------------------------------------------------------------------
#  Types
# ------------------------------------------------------------------------------------------------------------
schemas:
  subscriptionQuery: | 
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Subscription",
      "description": "A Request for Subscription",
      "type": "object",
      "properties": {
          "eventID": {
              "description": "The unique identifier for an event",
              "type": "string"
          }
      },
      "required": ["subID","eventID","callbackURL","healthURL"]
    }
  subsription: | 
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Subscription",
      "description": "A Request for Subscription",
      "type": "object",
      "properties": {
          "subID": {
              "description": "The unique identifier for a subscriber",
              "type": "string"
          },
          "eventID": {
              "description": "The unique identifier for an event",
              "type": "string"
          },
          "callbackURL": {
              "description": "Where the subscriber should be notified",
              "type": "string"
          },
          "healthURL": {
              "description": "Where the subscriber will provide a periodical health check.",
              "type": "string"
          }
      },
      "required": ["subID","eventID","callbackURL","healthURL"]
    }
  subscriptionStatus: | 
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Subscription Status",
      "description": "Status of a Subscription.",
      "type": "object",
      "properties": {
          "status": {
              "description": "Status Code",
              "type": "string"
          }
      },
      "required": ["status"]
    } 
  subscriptionsDetail: | 
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Subscription Status",
      "description": "Status of a Subscription.",
      "type": "array",
      "properties": {
          "subscriptions": {
              "description": "Status Code",
              "schema": "subsription"
          }
      },
      "required": ["subscriptionStatus"]
    }
  subscriptionUpdate: | 
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Update a Subscription",
      "description": "Status of a Subscription.",
      "type": "object",
      "properties": {
          "subscriptionQuery": {
              "description": "Subscription to Update.",
              "schema": "subscriptionQuery"
          },
          "eventSubscription": {
              "description": "New intented state for the identified subscription. If no value is sent on the subscriptionQuery, the subscription is deleted.",
              "schema": "eventSubscription"
          }
      },
      "required": ["subscriptionStatus"]
    }
# ------------------------------------------------------------------------------------------------------------

/event_subscription:
  get:
    queryParameters:
      event_id:
        description: "The unique identifier for an event"
        required: true
        minLength: 1
        type: string
        example: "MarioMesaglio.34503324"
    responses:
      200:
        body:
          application/json:
            schema: subscriptionsDetail
      404:
        body:
          application/json:
            schema: subscriptionStatus
  post:
    body:
     application/json:
      schema: subsription
    responses:
      200:
        body:
          application/json:
            schema: subscriptionStatus
  put:
    body:
     application/json:
      schema: subscriptionUpdate
    responses:
      200:
        body:
          application/json:
            schema: subscriptionStatus                        
      404:
        body:
          application/json:
            schema: subscriptionStatus
  